import Head from 'next/head';
import Image from 'next/image';
import Test1Component from '../components/Test1Component';
import Test2Component from '../components/Test2Component';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Test1Component />
            <Test2Component />
        </div>
    );
}
